ADDED

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -324,10 +324,12 @@ jobs:
           echo "AWS configuration:"
           aws configure list
           aws sts get-caller-identity
-          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
-          IMAGE_NAME="$ECR_REGISTRY/$ECR_REPOSITORY:latest"
+          echo "Logging in to ECR..."
+          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY || { echo "ECR login failed."; exit 1; }
+          echo "Pulling Docker image..."
+          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest || { echo "Failed to pull Docker image."; exit 1; }
           echo "Docker image name: $IMAGE_NAME"
-          docker pull $IMAGE_NAME
-          docker run -d -p 5000:5000 $ECR_REGISTRY/$ECR_REPOSITORY:latest
+          echo "Running Docker container..."
+          docker run -d -p 5000:5000 $ECR_REGISTRY/$ECR_REPOSITORY:latest || { echo "Failed to run Docker container."; exit 1; }
           docker ps
       
